ENT.Type = "anim";
ENT.Base = "base_gmodentity";
ENT.PrintName = "Lambda Base";
ENT.Author = "MegaDeath";
ENT.Contact = "MegaDeath409@gmail.com";
ENT.Purpose = "Base Unit for Lambda";
ENT.Instructions = "Doesn't actually do anything unless modified by an expansion script.";
ENT.Spawnable = false;
ENT.AdminSpawnable = true;
